language: haskell
ghc: 7.8

install:
  - cabal install --only-dependencies --enable-tests
  - cabal install hpc-coveralls QuickCheck quickcheck-instances hspec

script:
  - cabal configure --enable-tests --enable-library-coverage && cabal build
  - run-cabal-test --show-details=always

after_script:
  - hpc-coveralls --exclude-dir=test spec

branches:
  only:
    - master
