flags: {}
packages:
- '.'
- location:
    git: https://github.com/athanclark/path-extra
    commit: 5e510a949c5bcd79ac662b622a371c3403ffc474
  extra-dep: true


extra-deps:
  - path-extra-0.0.2
resolver: nightly-2015-10-01
